require(DIR_SCRIPT.."game/entity")
require(DIR_SCRIPT.."game/scene")
require(DIR_SCRIPT.."game/Timer")
require(DIR_SCRIPT.."game/logic")
require(DIR_SCRIPT.."game/Network")
require(DIR_SCRIPT.."game/network/Synchronizer")
require(DIR_SCRIPT.."game/sound")
